//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saga.GMD.Adobe.Anonymisation.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GMD_DWHEntities : DbContext
    {
        public GMD_DWHEntities()
            : base("name=GMD_DWHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ExtractRecipient> ExtractRecipients { get; set; }
        public virtual DbSet<ExtractCPRecipient> ExtractCPRecipients { get; set; }
    }
}
